server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/voting_db?currentSchema=auth_schema}
    username: ${SPRING_DATASOURCE_USERNAME:voting_user}
    password: ${SPRING_DATASOURCE_PASSWORD:voting_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_schema
  flyway:
    enabled: true
    schemas: auth_schema
    default-schema: auth_schema
    create-schemas: true

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000 # 1 day
