services:
  postgres:
    image: postgres:16-alpine
    container_name: voting-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: voting_db
      POSTGRES_USER: voting_user
      POSTGRES_PASSWORD: voting_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voting_user -d voting_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: voting-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: voting-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/voting_db
      SPRING_DATASOURCE_USERNAME: voting_user
      SPRING_DATASOURCE_PASSWORD: voting_pass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: azanovskiy04@gmail.com
      SPRING_MAIL_PASSWORD: epkvdvfubokctlyr
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
